//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Partner()
        {
            this.PartherProducts = new HashSet<PartherProducts>();
            this.PartherProducts1 = new HashSet<PartherProducts>();
        }
    
        public int ID { get; set; }
        public Nullable<int> IDType { get; set; }
        public string Name { get; set; }
        public string DirectorName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string INN { get; set; }
        public Nullable<int> Rating { get; set; }
        public string Logo { get; set; }

        public string CorrectLogo
        {
            get
            {
                if (Logo != null)
                {
                    return $"images/{Logo}";
                }
                else
                {
                    return $"images/picture.png";
                }
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartherProducts> PartherProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartherProducts> PartherProducts1 { get; set; }
        public virtual PartnerType PartnerType { get; set; }

        public virtual PartherProducts PartherProducts2 { get; set; }
    }
}
