//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp
{
    using System;
    using System.Collections.Generic;
    using System.Diagnostics.Eventing.Reader;

    public partial class PartherProducts
    {
        public int ID { get; set; }
        public string Production { get; set; }
        public Nullable<int> PartnerID { get; set; }
        public Nullable<int> ProductionQuantity { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
    
        public virtual Partner Partner { get; set; }
        public virtual Partner Partner1 { get; set; }

        public string SalesPercent
        {
            get
            {
                if (ProductionQuantity <= 10000)
                {
                    return "0%";
                }
                else if (ProductionQuantity <= 50000)
                {
                    return "5%";
                }
                else if ((ProductionQuantity <= 300000))
                {
                    return "10%";
                }
                else
                {
                    return "15%";
                }
            }
        }

    }
}
