//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartnersApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Name { get; set; }
        public string Articul { get; set; }
        public Nullable<decimal> MinCostForPartner { get; set; }
    
        public virtual ProductType ProductType { get; set; }
    }
}
